name:                pixie
version:             0.1.0.0
github:              "mesabloo/pixie"
license:             BSD3
author:              "Mesabloo"
maintainer:          "example@example.com"
copyright:           "2019 Mesabloo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mesabloo/pixie#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 7
- parser-combinators
- optparse-applicative
- text
- raw-strings-qq
- ansi-terminal
- mtl
- containers
- wl-pprint

library:
  source-dirs: src

executables:
  pixie-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixie

tests:
  pixie-unit-tests:
    main:        Spec.hs               
    source-dirs:
    - test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixie
    - keys
    - ansi-terminal
    - wl-pprint
    - optparse-applicative
